// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB93f1Au1aKv9wydTQIo-0XrNaVo7rSBe0',
    appId: '1:590620223268:web:c9c6c6b4284253a17db5b1',
    messagingSenderId: '590620223268',
    projectId: 'gdsc-kw-solution',
    authDomain: 'gdsc-kw-solution.firebaseapp.com',
    storageBucket: 'gdsc-kw-solution.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClLJPEDZuVbGoR3H9cCMNEcz8q4D3ChUI',
    appId: '1:590620223268:android:482421a88e1a804e7db5b1',
    messagingSenderId: '590620223268',
    projectId: 'gdsc-kw-solution',
    storageBucket: 'gdsc-kw-solution.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDr6q7iO5v94W1hET_v0LshMUNy2mGMkU',
    appId: '1:590620223268:ios:ac6c15fee12c1c5f7db5b1',
    messagingSenderId: '590620223268',
    projectId: 'gdsc-kw-solution',
    storageBucket: 'gdsc-kw-solution.appspot.com',
    iosBundleId: 'com.example.gdscSolutionProject',
  );
}
