// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7sr7JYcMvDt-m4ZywjRl-4HZWD925iRo',
    appId: '1:856991396566:web:8adcea24a53f92ff7c8f77',
    messagingSenderId: '856991396566',
    projectId: 'solution-1954e',
    authDomain: 'solution-1954e.firebaseapp.com',
    storageBucket: 'solution-1954e.appspot.com',
    measurementId: 'G-5TE0XRYL84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3FNvjC5kuzFctk1-wlR0N-cUPuMMwqKg',
    appId: '1:856991396566:android:afdf427743bb92297c8f77',
    messagingSenderId: '856991396566',
    projectId: 'solution-1954e',
    storageBucket: 'solution-1954e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHe77KYkoIr2ZUcegYFGvQFxcW3syyF8M',
    appId: '1:856991396566:ios:935ba2dc61716aad7c8f77',
    messagingSenderId: '856991396566',
    projectId: 'solution-1954e',
    storageBucket: 'solution-1954e.appspot.com',
    iosBundleId: 'com.example.gdscSolutionProject',
  );
}
